apiVersion: v1
kind: PersistentVolume
metadata:
  name: guest-book-db-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/storages/guest_book_db