apiVersion: v1
kind: Service
metadata:
  name: guest-book-db
spec:
  selector:
    app: guest-book
    role: database
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: gwdb-port
