server:
  port: 8150
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: "${SSL_KEYSTORE:/usr/share/key-stores/osk-keytore.p12}"
    key-password: "${SSL_KEY_PASSWORD:change-me}"
    key-store-password: "${SSL_KEYSTORE_PASSWORD:change-me}"
    keyStoreType: PKCS12

spring:
  data:
    mongodb:
      uri: "mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017},${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/guest-book?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000"
      database: guest-book

info:
  app:
    name: @project.name@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

management:
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
